public with sharing class Eventattendeesbooleans {
public Boolean ReqFields{get; set;}
    public Boolean Prefix{get; set;}
    public Boolean FirstName{get; set;}
    public Boolean LastName{get; set;}
    public Boolean sufix{get; set;}
    public Boolean emailID{get; set;}
    public Boolean CompanyName{get; set;}
    public Boolean Degi{get; set;}
    public Boolean mobile{get; set;}
    public Boolean age{get; set;}
    public Boolean gen{get; set;}
    public Boolean dob{get; set;}
    public Boolean homeinfo{get; set;}
    public Boolean Shippinginfo{get; set;}
    public Boolean workinfo{get; set;}
    public Boolean NAICSCode1{get; set;}
    public Boolean NAICSCode2{get; set;}
    public Boolean NAICSCode3{get; set;}
    public Boolean PBC{get; set;}
    public Boolean SBC{get; set;}
    public Boolean NOEmp{get; set;}
    public Boolean BEDate{get; set;}
    public Boolean BRev{get; set;}
    public Boolean BTaxID{get; set;}
    public Boolean BDN{get; set;}
    public Boolean webUrl{get; set;}
    public Boolean blogUrl{get; set;}
    public Boolean DT{get; set;}
    public Boolean BDesc{get; set;}
    public Boolean BusinessBool{get; set;}
    public Boolean NAICSCOdes{get; set;}
    public Boolean AttendeePic{get; set;}
    
public Eventattendeesbooleans (){
ReqFields=true;
Prefix=true;
FirstName=true;
LastName=true;
sufix=true;
emailID=true;
CompanyName=true;
mobile=true;
Degi=true;
age=true;
gen=true;
dob=true;
homeinfo=true;
Shippinginfo=true;
workinfo=true;
NAICSCode1=true;
NAICSCode2=true;
NAICSCode3=true;
PBC=true;
SBC=true;
NOEmp=true;
BEDate=true;
BRev=true;
BTaxID=true;
BDN=true;
webUrl=true;
blogUrl=true;
DT=true;
BDesc=true;
BusinessBool=true;
NAICSCOdes=true;
AttendeePic=true;

}

}