public with sharing class sampleapgeUrl {


public void send(){

  String EmailBody = 'We are working with BoothLeads to help you with your event '+ 'Phani Event'+'. All badges will now have a QR code specific to your name and company.You will be able to scan the QR code on-site,make notes about that individual and follow up with them.'+'\n\n'+'You have been added to the BoothLeads database for '+  'Phani Event'+'<u><b> Now what?</b></u>'
+'\n\n\n'+'<ul> Go to http://www.boothleads.com to login into your Booth admin Portal as well as your mobile app. <b>Username and Password are provided at the bottom of this email.</b></ul>'
+'\n\n'+' Here are some youtube videos to give you an idea of what will happen:'+'\n\n'+' o What is a QR code: http://www.youtube.com/watch?v=b8EpazIwFys'+'\n\n'+' o How to use Booth Admin Portal :  http://www.youtube.com/watch?v=jcg2qbS_TaM&feature=youtu.be'
+'\n\n'+'<ul> Next step….Download the appropriate app to your phone either from Google Play Store or AppStore or BlackBerry World.</ul>'
+'\n\n'+'Then you are ready to scan the badges on-site!'+'\n\n'+'Please note that your Booth Leads portal access is valid only for 30 days from the end of your event'
+'\n\n'+ 'Please remember to export all your leads.'+'\n\n'+'If you need access beyond this, please contact support.'+'\n\n'+'Thank you!'+'\n'+'BoothLeads Customer Support'+'\n'+'support@boothleads.com';
      
         
 String EmailSubject = 'Booth Leads and '+ 'Phani Event';


}



}